- name: "[main_requirements] - Check assertions"
  ansible.builtin.assert:
    that: "{{ assertion.that }}"
    fail_msg: "{{ assertion.fail_msg }}"
    success_msg: "{{ assertion.success_msg }}"
    quiet: yes
  loop_control:
    loop_var: assertion
    label: "Assert {{ assertion.that }}" 
  loop:
    - {
        that: "available_actions is defined",
        fail_msg: "You must defined available_actions, please refer to the documentation.",
        success_msg: "avaible_actions is defined."
      }
    - { 
        that: "trigger_action in available_actions", 
        fail_msg: "You must set a valid action in available_actions before launch this role. Please refer to the documentation.",
        success_msg: "Action {{ trigger_action }} is valid."
      }